# Generated by Django 5.0.1 on 2024-08-14 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название записи')),
                ('text', models.TextField(verbose_name='Текст записи')),
                ('image', models.ImageField(blank=True, default='diary/diary_entry/default.png', null=True, upload_to='diary/diary_entry', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('is_published', models.BooleanField(default=True, verbose_name='Статус публикации')),
            ],
            options={
                'verbose_name': 'Запись',
                'verbose_name_plural': 'Записи',
                'db_table': '_d_diary_entry',
                'db_table_comment': 'Записи в дневнике',
                'ordering': ['author', 'updated_at'],
            },
        ),
    ]
